### ISSUE TITLE
Cache purge failed on the 0.19.1-beta.1 release

### ISSUE THREAD

**Issue by AlexIIL** [QuiltMC/update-quilt-meta#10]
I'm assuming this isn't actually that important (since I guess the caches will be refreshed *eventually*) but I'm still reporting this nonetheless.

https://github.com/QuiltMC/quilt-loader/actions/runs/5239220513/jobs/9458852510

> java.lang.RuntimeException: Failed to purge batch 15 (status code 500): {"success":false,"errors":[{"code":1015,"message":"Unable to purge. Internal error."}],"messages":[],"result":null}
Error:  Failed to build meta. Please refer to the logs and report this to the Infrastructure team.
	at org.quiltmc.Main.purgeCache(Main.java:561)
	at org.quiltmc.Main.build(Main.java:126)
	at org.quiltmc.Main.main(Main.java:58)

**Comment by eristhea** [comment]
i'm going to close this issue as it seems to be a one-time thing. will reopen if we ever see this again!
